custom_components/victron/const.py

The unit should be None in that case and not an empty string.
Fixes #22
* `unit=""` should be used for numerical entities without unit
* `unit=None` should be used for non-numerical entities

Fixed handling of non-numeric entities

---

custom_components/victron/coordinator.py

This displays strings properly instead of as bytes (b'something').

Decode strings from bytes

---

custom_components/victron/manifest.json
custom_components/victron/sensor.py

Tank based entities have volume based entities.
However, these entities should be storage based instead of consumption based.
This PR should address (at least in part) issue #62

Change volume class to volume storage

---

custom_components/victron/manifest.json

HA Core has been updated to pymodbus library version 3.4.1.
This PR aligns the pymodbus versions so that core modbus integration and this integration remain interoperable.

Bump pymodbus to version 3.4.1

---

custom_components/victron/coordinator.py
custom_components/victron/manifest.json
hacs.json

Bump pymodbus and ha core minimum version requirement due to breaking core pymodbus patch (endian spelling)

Bump pymodbus 3.5.1 for 2023.9 patch compatibility

---

custom_components/victron/const.py
custom_components/victron/number.py
custom_components/victron/sensor.py

this should address issue #154
please run some tests before merging, since I do not have any victron installed so far and therefore cannot do tests,

Fixing depricated constants in HA 2024.1

---

custom_components/victron/const.py

to reflect the new specsheet that was published we need to change the unit of measurement from meters per seconds to meters for gps altitude register. Solves #28 
Unfortunatly it isn't possible to migrate the unit for historical data.
So users should go to "developer tools -> statistics" and press "Fix Issue" to ensure long term statistics are generated again.

Change gps altitude register from meters per seconds to meters

---

custom_components/victron/sensor.py

Battery soc in general overview is incorrectly reporting 0% due to non SOC related entities getting assigned with the battery device class.
Allowing them to be selected by HA as the devices current SOC to be displayed #130.
This PR only assigns SOC entities the battery device class and sets no device class for other percentage based entities that aren't of type moisture, humidity or state of charge.

Only assign device class battery to entities measured in percentages

---

custom_components/victron/sensor.py

Handle unknown enum values gracefully by logging an error while not stopping all entity updates. #186

handle enum decoding gracefully instead of stopping all entity updates

---

custom_components/victron/sensor.py

create an set of integer values for the can i decode this test

---

custom_components/victron/const.py

base the ess mode values on attributes csv file from victron instead of xlsx.
This PR addresses: #44.
The values that are present in the attributes.csv also better match the values that are selecteable in the GX device itself:

add ess mode 0

---

custom_components/victron/const.py

support error status being returned for tank sensors. which is an undocumented value.
Addresses #102

add status code 5 support for tanks

---

custom_components/victron/const.py

Use the attributes.csv definition as the main definition for decoding dcsource registers.
Addresses: #27.

Decode startervoltage with factor of 10 instead of 100

---

custom_components/victron/const.py

use the bluesolar hex protocol to detemine status code 245 meaning since it is not documented in the official xlsx.
Addresses: #178

add solarcharger state 245 as wake up

---

custom_components/victron/binary_sensor.py
custom_components/victron/button.py
custom_components/victron/number.py
custom_components/victron/select.py
custom_components/victron/switch.py

splitting devices by name will end the flip flopping of device names when different type register set namings are used

split devices by a combination of unit id and name

---

custom_components/victron/binary_sensor.py
custom_components/victron/button.py
custom_components/victron/hub.py
custom_components/victron/number.py
custom_components/victron/select.py
custom_components/victron/sensor.py
custom_components/victron/switch.py

removes old testing code that is obsolete now that there is another way of seperating unit id 0 and 100 devices

cleanup the device seperation obsolete code

---

custom_components/victron/coordinator.py
custom_components/victron/hub.py

As discussed with @remcom this PR will be the start of backporting fixes made on the remcom fork.
This pr limits itself to only the code necessarry to be able to run this integration on homeassistant 2025.2
This needs to be merged before 5 februari (release date of ha 2025.2)

backport 2025.2 from remcom fork

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/change_request.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR introduces new templates for bug, changes and feature request issues.
It replaces the current issue template format since github can't seem to parse it.
Adds issue templates for different issue types to allow for quicker troubleshooting of users issues.
Since this enforces the first couple of troubleshooting steps to be performed before submitting an issue and thereby saving time.
- This PR fixes or closes issue: None
- This PR is related to issue: None
- Link to documentation pull request: None

Add bug, feature and change request issue templates since present template isn't working

---

.github/workflows/hassfest.yml
.github/workflows/release-drafter.yaml
.github/workflows/ruff.yaml
.github/workflows/stale.yaml

Bumping all of the github actions.
Stale actions seems to contain a bug on v3.0.0 that won't remove stale labels upon a comment.
- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

bump stale bot due to removal not working and bumping all other actions

---

README.md

Hey, thanks for the project.
I just used the instructions from "Manual" to successfully integrate victron data into home assistant.
Update README.md: 
- clarified the manual installation 
- corrected some typos
No Breaking changes.
Update Readme
No additional information.

Update README.md: clarified the manual installation and corrected some typos

---

custom_components/victron/hub.py
custom_components/victron/manifest.json
hacs.json

Add additional logic to allow installations from ha core 2025.2 til 2025.7 (pymodbus 3.8 till 3.9.2)
- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

initial attempt at supporting core 2025.2 till 2025.6 and 2025.7
